name: CI-Tests

# Run this workflow every time a new commit pushed to your repository
on:
  push:
  pull_request:
    branches:
    - master

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  unit-tests:
    # Name the Job
    name: Run tests
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: go test ./...
      - run: go build -o cosign ./cmd/
